version: '2'

volumes:
    prometheus_data:
      driver: rancher-nfs
    grafana_data:
      driver: rancher-nfs

services:

  prometheus:
    image: image.token.im/consenlabs/prometheus
    container_name: prometheus
    volumes:
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-web.console.libraries=/etc/prometheus/console_libraries'
      - '-web.console.templates=/etc/prometheus/consoles'
      - '-alertmanager.url=http://alertmanager:9093'
      - '-storage.local.target-heap-size=1073741824'
      - '-storage.local.retention=200h'
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  alertmanager:
    image: image.token.im/consenlabs/alertmanager
    container_name: alertmanager
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  nodeexporter:
    image: prom/node-exporter:v0.15.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  cadvisor:
    image: google/cadvisor:v0.27.1
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped
    labels:
      io.rancher.scheduler.global: 'true'
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file: .env_grafana
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"

  caddy:
    image: image.token.im/consenlabs/caddy
    container_name: caddy
    ports:
      - "3000:3000"
      - "9090:9090"
      - "9093:9093"
    env_file: .env_caddy
    restart: unless-stopped
    labels:
      org.label-schema.group: "monitoring"


